import type { SkillGroupModel } from "../types";

export const skills: SkillGroupModel[] = [
  {
    title: "Ключевая экспертиза",
    emphasis: "core",
    items: [
      { name: "React.js", featured: true },
      { name: "Next.js", featured: true },
      { name: "TypeScript", featured: true },
      { name: "Tailwind CSS", featured: true },
      { name: "Storybook", featured: true },
      { name: "Redux Toolkit", featured: true },
      { name: "Zustand", featured: true },
      { name: "Vitest", featured: true },
      { name: "Webpack", featured: true },
      { name: "React Testing Library", featured: true },
      { name: "Node.js", featured: true },
    ],
  },
  {
    title: "Архитектура и инженерия",
    emphasis: "standard",
    items: [
      { name: "Фронтенд-архитектура" },
      { name: "Дизайн-системы" },
      { name: "Developer Experience" },
      { name: "Оптимизация производительности" },
      { name: "Масштабируемые UI-системы" },
      { name: "Доступность (a11y)" },
      { name: "Инструменты сборки" },
      { name: "Модернизация legacy" },
      { name: "CI/CD" },
    ],
  },
  {
    title: "Платформы и домены",
    emphasis: "standard",
    items: [
      { name: "Vercel" },
      { name: "Supabase" },
      { name: "Firebase" },
      { name: "Sitecore CMS" },
      { name: "Drupal" },
      { name: "Микрофронтенды" },
      { name: "FinTech" },
      { name: "Real-time приложения" },
    ],
  },
  {
    title: "Раньше работал с",
    emphasis: "muted",
    collapsible: true,
    items: [
      { name: "Ember.js" },
      { name: "CoffeeScript" },
      { name: "jQuery" },
      { name: "Handlebars" },
      { name: "Bootstrap" },
      { name: "Chakra UI" },
      { name: "SCSS" },
      { name: "PostCSS" },
      { name: "Vite" },
      { name: "Parcel" },
      { name: "EsBuild" },
      { name: "MongoDB" },
    ],
  },
  {
    title: "Языки",
    emphasis: "languages",
    items: [{ name: "Русский — родной" }, { name: "Английский — B2+" }, { name: "Польский — B1+" }],
  },
];
