import type { ExperienceItemModel } from "../types";

export const experience: ExperienceItemModel[] = [
  {
    company: "StoneX Group Inc.",
    role: "Front-end Engineer",
    period: { start: "2024-11", end: "2026-03", label: "Nov 2024 — Present" },
    location: "Cracow, Poland",
    summary:
      "Business-critical FinTech product on legacy Sitecore CMS, .NET, native JavaScript and Preact, mid-migration to a modern React / Next.js / Tailwind stack across three frontend squads. Joined mid-stage — platform architecture was already set; my focus is landing component-level migration and reliability of the new stack.",
    responsibilities: [
      "Frontend engineer in a 4-developer + 2-QA squad.",
      "Own migration of major UI components from the legacy stack to React / Storybook / Tailwind.",
      "Built and maintain an internal client wrapping the Lightstreamer SDK for real-time data, used across multiple components.",
      "Act as one of the core required reviewers — without my +1, code does not merge.",
      "Mentor 1-2 juniors and currently organising an internal frontend community across squads and geographies.",
    ],
    achievements: [
      "Migrated 10-15 major components (skeletons, tables, composite molecules) to the new stack — base atoms not included.",
      "Shipped internal Lightstreamer SDK client adopted by multiple components for real-time data flow.",
      "Defended and shipped ~5 of ~8 POCs in six months (~60% adoption rate).",
      "Review 2-4 PRs per day as a required reviewer — gating quality at merge time.",
    ],
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Storybook",
      "Lightstreamer SDK",
      "Sitecore CMS",
      ".NET",
      "Preact",
      "Uniform.dev",
      "Kontent.ai",
      "GitHub",
      "Vercel",
    ],
    featured: true,
  },
  {
    company: "Synder",
    role: "Senior Front-end Engineer",
    period: { start: "2023-11", end: "2024-09", label: "Nov 2023 — Sep 2024" },
    location: "Cracow, Poland",
    summary:
      "Senior FE role across four microfrontend products built on different React versions, with inconsistent component states and varying levels of implementation. The product needed both day-to-day delivery and longer-term consolidation of frontend standards.",
    responsibilities: [
      "Collaborated with product owners, backend engineers, designers and QA across four parallel products.",
      "Owned ESLint configuration overhaul end-to-end.",
      "Pitched and led a Component Library proposal — research, leadership pitch, design-team alignment, first demo components.",
      "Conducted regular code reviews and contributed to frontend best practices.",
      "Shipped new pages and frontend services to expand product functionality.",
    ],
    achievements: [
      "ESLint overhaul (automated import sorting + stricter validation rules) cut PR review cycle by 30-40%.",
      "Component Library proposal accepted by leadership; established working channel with the design team and shipped first demo components.",
      "Worked across four products on different React versions without forcing premature consolidation — pragmatic over ideological.",
    ],
    technologies: ["React", "Redux", "RTK Query", "TypeScript", "ESLint", "Microfrontends"],
    featured: true,
  },
  {
    company: "Monterosa",
    role: "Front-end Engineer",
    period: { start: "2019-01", end: "2023-09", label: "Jan 2019 — Sep 2023" },
    location: "Minsk → Cracow",
    summary:
      "Real-time engagement platform with a legacy Ember.js codebase and an evolving design system. The team needed both modernisation (Ember → React) and a unified UI direction. Joined the team from Minsk in January 2019; relocated to Cracow in March 2022 and continued on the same team with the same scope and delivery cadence.",
    responsibilities: [
      "Owned the design-system rewrite to the new visual language.",
      "Refactored the legacy Ember.js codebase for performance and maintainability.",
      "Built and integrated React.js modules during progressive migration.",
      "Wrote unit tests for new React modules and conducted code reviews.",
      "Worked across Ember.js, React.js, TypeScript, SCSS, Handlebars, CoffeeScript and Zustand on the same product.",
    ],
    achievements: [
      "Fully rewrote the design system to the new visual language; improved component file structure and accelerated project build.",
      "Delivered 20% performance gain on the legacy Ember.js codebase through targeted optimisation and refactoring.",
      "Achieved 80-85%+ unit test coverage on the new React.js modules.",
      "4+ year tenure on the same team — endorsed by the CTO and Engineering Lead as a high-trust contributor.",
    ],
    technologies: [
      "Ember.js",
      "React",
      "TypeScript",
      "JavaScript",
      "CoffeeScript",
      "SCSS",
      "Handlebars",
      "Zustand",
      "Jest",
      "React Testing Library",
    ],
    featured: true,
  },
  {
    company: "Belitsoft",
    role: "Front-end Developer",
    period: { start: "2014-08", end: "2018-12", label: "Aug 2014 — Dec 2018" },
    location: "Minsk, Belarus",
    summary:
      "Long-term and short-term frontend work for CMS-based platforms and reusable component libraries — including the Bossrevolution and WebMD platforms and the Lundberg Design site.",
    responsibilities: [
      "Developed maintainable, cross-browser web applications.",
      "Created reusable components for faster integration of similar features.",
      "Built complex animations and added test coverage.",
      "Developed Drupal-based components, admin panel parts, modules, and CKEditor 4.x plugin integrations.",
    ],
    achievements: [
      "Played a key role in the Bossrevolution project, improving user experience.",
      "Trained and supervised junior colleagues.",
      "Contributed to WebMD and Lundberg Design.",
    ],
    technologies: ["HTML", "CSS", "JavaScript", "Drupal", "CKEditor API", "Animations", "Testing"],
  },
  {
    company: "Earlier Career",
    role: "Front-end Developer",
    period: { start: "2011-07", end: "2014-08", label: "2011 — 2014" },
    location: "Belarus",
    summary:
      "Three years of foundational frontend work across Belitsoft (2011-2013), Startup Labs (2012-2013) and EPAM Systems (2013-2014) — including the Fishpond.com.au Australian online store client engagement (with Belitsoft), corporate and advertising sites at EPAM, and reusable component work that became the foundation for the senior career since 2014.",
    responsibilities: [],
    achievements: [],
    technologies: ["HTML", "CSS", "JavaScript", "jQuery"],
  },
];
