import type { SkillGroupModel } from "../types";

export const skills: SkillGroupModel[] = [
  {
    title: "Core Expertise",
    emphasis: "core",
    items: [
      { name: "React.js", featured: true },
      { name: "Next.js", featured: true },
      { name: "TypeScript", featured: true },
      { name: "Tailwind CSS", featured: true },
      { name: "Storybook", featured: true },
      { name: "Redux Toolkit", featured: true },
      { name: "Zustand", featured: true },
      { name: "Vitest", featured: true },
      { name: "Webpack", featured: true },
      { name: "React Testing Library", featured: true },
      { name: "Node.js", featured: true },
    ],
  },
  {
    title: "Architecture & Engineering",
    emphasis: "standard",
    items: [
      { name: "Frontend Architecture" },
      { name: "Design Systems" },
      { name: "Developer Experience" },
      { name: "Performance Optimization" },
      { name: "Scalable UI Systems" },
      { name: "Accessibility" },
      { name: "Build Tooling" },
      { name: "Legacy Modernization" },
      { name: "CI/CD" },
    ],
  },
  {
    title: "Platforms & Domains",
    emphasis: "standard",
    items: [
      { name: "Vercel" },
      { name: "Supabase" },
      { name: "Firebase" },
      { name: "Sitecore CMS" },
      { name: "Drupal" },
      { name: "Microfrontends" },
      { name: "FinTech" },
      { name: "Real-time Applications" },
    ],
  },
  {
    title: "Previously worked with",
    emphasis: "muted",
    collapsible: true,
    items: [
      { name: "Ember.js" },
      { name: "CoffeeScript" },
      { name: "jQuery" },
      { name: "Handlebars" },
      { name: "Bootstrap" },
      { name: "Chakra UI" },
      { name: "SCSS" },
      { name: "PostCSS" },
      { name: "Vite" },
      { name: "Parcel" },
      { name: "EsBuild" },
      { name: "MongoDB" },
    ],
  },
  {
    title: "Languages",
    emphasis: "languages",
    items: [{ name: "Russian — Native" }, { name: "English — B2+" }, { name: "Polish — B1+" }],
  },
];
