import type { UiModel } from "../types";

export const ui: UiModel = {
  sections: {
    about: { eyebrow: "01 / About", title: "About" },
    experience: { eyebrow: "02 / Experience", title: "Experience" },
    leadership: { eyebrow: "03 / Leadership", title: "Leadership & Engineering Impact" },
    projects: { eyebrow: "04 / Projects", title: "Projects" },
    principles: { eyebrow: "05 / Principles", title: "How I Build Software" },
    teaching: { eyebrow: "06 / Teaching", title: "Teaching & Mentoring" },
    testimonials: { eyebrow: "07 / Testimonials", title: "What People Say" },
    skills: { eyebrow: "08 / Skills", title: "Skills & Expertise" },
    certifications: { eyebrow: "09 / Certifications", title: "Certifications" },
    education: { eyebrow: "10 / Education", title: "Education" },
    contact: { eyebrow: "11 / Contact" },
  },
  labels: {
    highlights: "Highlights",
    outcome: "Outcome",
    role: "Role",
    context: "Context",
    action: "Action",
    impact: "Impact",
    principle: "Principle",
    courses: "Courses",
    topics: "Topics",
    viewCredential: "View credential",
  },
  statusLabels: {
    "open-to-work": "Open to work",
    "open-to-projects": "Looking for interesting projects",
    "open-to-offers": "Open to offers",
    "not-looking": "Not looking for work",
    "available-remote": "Available for remote",
    "available-hybrid": "Available for hybrid",
    "available-onsite": "Available for on-site",
    consulting: "Available for consulting",
    freelance: "Available for freelance / contract",
    mentoring: "Open to mentoring",
    relocatable: "Open to relocation",
  },
  leadershipStatus: {
    ongoing: "In flight",
    delivered: "Delivered",
  },
  testimonialsNote: {
    prefix: "More recommendations available on",
    linkLabel: "LinkedIn",
    suffix: ".",
  },
  localeSwitcher: {
    ariaLabel: "Language",
    names: { en: "EN", ru: "RU", pl: "PL", be: "BE" },
  },
  a11y: {
    primaryNav: "Primary",
    mobileNav: "Mobile",
    openMenu: "Open menu",
    switchToLightTheme: "Switch to light theme",
    switchToDarkTheme: "Switch to dark theme",
    viewCredential: "View {title} credential",
  },
};
